### PR TITLE
Fix package name in build scripts

### PR DESCRIPTION
**Pull request by nberth**

### CODE REVIEW

**Review by emilienlemaire — APPROVED** [review]
All good, I thought I already changed those 😅
Ok to merge after CI passed 👍

**Comment by nberth** [comment]
Actually what is the CI doing? Is it supposed to reach the `make compile` stage?

**Comment by emilienlemaire** [comment]
As of now it just does a `drom build`, but that  has been useful to check if everything compiled well on windows

**Comment by nberth** [comment]
Do you think it's relevant to complete the build process in the CI (with yarn and all)?

**Comment by emilienlemaire** [comment]
It would be for deployment maybe, to generate the `.vsix` file automatically, but for now it will just slow down the CI which is already not that fast

**Comment by nberth** [comment]
Ok, for a deployment test maybe. That was just to check what the CI is used for.

**Pull request merged**
